
eureka:
  client:
    serice-url:
      default-zone : http://localhost:8761/eureka
spring:
  jpa:
    show-sql: true
  application:
    name : forex-service
  h2:
    console:
      enabled: true
server:
  port : 8000






